### ISSUE TITLE
No Target_function in XML Report

### ISSUE THREAD

**Issue by tremo-zz** [moloch--/Fortify-XML-Converter#1]
C:\FortifyXMLparser>python fxml2xlsx.py -i fGenis.xml -o deneme -f csv
[*] Parsing issue 1 of 8 ...Traceback (most recent call last):
  File "fxml2xlsx.py", line 310, in <module>
    main(args)
  File "fxml2xlsx.py", line 278, in main
    formats[args.format](args.output)
  File "fxml2xlsx.py", line 145, in to_csv
    for vuln in self.ordered_findings:
  File "fxml2xlsx.py", line 130, in ordered_findings
    for risk_level in self.findings:
  File "fxml2xlsx.py", line 103, in findings
    self._generate_findings()
  File "fxml2xlsx.py", line 119, in _generate_findings
    target_function=primary.findtext("TargetFunction"),
  File "fxml2xlsx.py", line 62, in __init__
    self.target_function = kwargs.get('target_function', '').strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by moloch--** [comment]
I added a check for `None`, let me know if that fixes the issue.
