### ISSUE TITLE
Convertion not working. Need urgent help

### ISSUE THREAD

**Issue by PavitraRaj** [moloch--/Fortify-XML-Converter#2]
Hi,

When i tried to convert xml data to csv, it gives the following error.
Please help me proceed further.
[*] Parsing issue 495 of 495 ...Traceback (most recent call last):
  File "C:\Users\PB033125\Downloads\Fortify-XML-Converter-master\Fortify-XML-Converter-master\fxml2xlsx.py", line 311, in <module>
    main(args)
  File "C:\Users\PB033125\Downloads\Fortify-XML-Converter-master\Fortify-XML-Converter-master\fxml2xlsx.py", line 279, in main
    formats[args.format](args.output)
  File "C:\Users\PB033125\Downloads\Fortify-XML-Converter-master\Fortify-XML-Converter-master\fxml2xlsx.py", line 146, in to_csv
    for vuln in self.ordered_findings:
  File "C:\Users\PB033125\Downloads\Fortify-XML-Converter-master\Fortify-XML-Converter-master\fxml2xlsx.py", line 133, in ordered_findings
    self._ordered_findings = sorted(master)
TypeError: '<' not supported between instances of 'Finding' and 'Finding'

**Comment by moloch--** [comment]
Sounds like Fortify did not properly escape some of the values when it generated the XML doc, you may need to manually edit the xml so that it parses correctly.

**Comment by PavitraRaj** [comment]
We are planning to convert Fortify reports from xml to csv automatically so that we can import the csv format  to DefectDOJO tool to display the report. If this convertion requires manual interruption, how shall we proceed in automating the process. Please suggest.
